config/routes.rb
Rails.application.routes.draw do
  match "/contacts/:importer/callback" => "google#index", :via => [:get]
  match "/oauth2callback" => "google#contact", :via => [:get]
  resources :companies
  resources :users
  devise_for :users, path: 'accounts', controllers: {omniauth_callbacks: "omniauth_callbacks"}
  root to: "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
   has_many :users, dependent: :nullify

   validates :name, presence: true, uniqueness: true
   validates :address, presence: true
   validates :city, presence: true
   validates :state, presence: true
   validates :commercial_activity, presence: true
   validates :cellphone, presence: true
   validates :phone, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable 
  belongs_to :company, optional: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable, omniauth_providers: [:google_oauth2, :facebook, :github]
  validates :first_name, presence: true
  validates  :last_name, presence: true
  validates  :address, presence: true
  validates  :password, presence: true
  validates  :email, presence: true
  validates  :city, presence: true
  validates  :state, presence: true
  validates  :cellphone, presence: true

   def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do | user |
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
      user.save!(:validate => false)
    end
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, except: [:index, :new, :create]
  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def update
   if @company.update(company_params)
      redirect_to @company
    else
      render 'edit'
    end
  end

  def create 
    @company = Company.new(company_params)
    if @company.save
      redirect_to @company
    else
      render 'new'
    end
  end

  def destroy
    @company.destroy
    redirect_to companies_path
  end

  private

  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(
      :name,
      :address,
      :city,
      :state,
      :commercial_activity,
      :cellphone,
      :phone
    )
  end
end

app/controllers/google_controller.rb
class GoogleController < ApplicationController
  def index
  end

  def contact
    @contacts = request.env['omnicontacts.contacts']
    respond_to do |format|
      format.html 
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController

  def google_oauth2
    auth = request.env["omniauth.auth"]
    user = User.where(provider: auth["provider"], uid: auth["uid"])
            .first_or_initialize(email: auth["info"]["email"])
    user.save!(:validate => false)

    user.remember_me = true
    sign_in(:user, user)

    redirect_to after_sign_in_path_for(user)
  end

  def facebook
    @user = User.create_from_provider_data(request.env['omniauth.auth'])
      if @user.persisted?
        sign_in_and_redirect @user
      else
        flash[:error] = 'There was a problem signing you in through Facebook. Please register or try signing in later.'
        redirect_to new_user_registration_url
      end 
  end

  def github
  @user = User.create_from_provider_data(request.env['omniauth.auth'])
  if @user.persisted?
    sign_in_and_redirect @user
  else
    flash[:error] = 'There was a problem signing you in through Github. Please register or try signing in later.'
    redirect_to new_user_registration_url
  end
end


  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_user, except: [:index, :new, :create]
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = current_user.user.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def set_user
   @user = User.find(params[:id]) 
  end

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :address,
      :password,
      :email,
      :city,
      :state,
      :cellphone,
      :phone,
      :company_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/google_helper.rb
module GoogleHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
 <div>
    <%= form_for(@company) do |c| %>
      <% @company.errors.full_messages.each do |message| %>
        <p style="padding: 2px; background-color: #25639E; display: table;"><%= message %><p>
      <% end %>
        Name :  <%= c.text_field :name %><br><br>
        Address :   <%= c.text_field :address %><br><br>
        City :     <%= c.text_field :city %><br><br>
        State :    <%= c.text_field :state %><br><br>
        Commercial Activity : <%= c.text_field :commercial_activity %><br><br>
        Cellphone :   <%= c.text_field :cellphone %><br><br>
        Phone :   <%= c.text_field :phone %><br><br>
        <%= c.submit %>
    <% end %>
    <%= link_to 'Volver', companies_path %>
</div>

app/views/companies/edit.html.erb
<h1>Edit company</h1>
<%= render 'form' %>

app/views/companies/index.html.erb
<div class="w3-container w3-container w3-center w3-animate-opacity w3-flat-midnight-blue">
 <h1>Companies</h1>
<table class="w3-table">
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Commercial Activity</th>
    <th>Cellphhone</th>
    <th>Phone</th>
    <th colspan="4"></th>
  </tr>
 
  <% @companies.each do |comp| %>
    <tr>
      <td><%= comp.name %></td>
      <td><%= comp.address %></td>
      <td><%= comp.city %></td>
      <td><%= comp.state %></td>
      <td><%= comp.commercial_activity %></td>
      <td><%= comp.cellphone %></td>
      <td><%= comp.phone %></td>
      <td>
        <%= link_to 'Show', comp %>
        <%= link_to 'Edit company', edit_company_path(comp) %>
        <%= link_to 'Delete company', comp,
                    method: :delete,
                    data: { confirm: '¿Are you sure?'} %>
      </td>

    </tr>
  <% end %>
  <%= link_to 'New company', new_company_path %> | <%= link_to 'USERS', users_path %>
</table>
</div>

app/views/companies/new.html.erb
 <h1>New company</h1>
<%= render 'form' %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>
<p><%= @company.address %></p>
<p><%= @company.city %></p>
<p><%= @company.state %></p>
<p><%= @company.commercial_activity %></p>
<p><%= @company.cellphone %></p>
<p><%= @company.phone %></p>
<h3><%= time_ago_in_words(@company.updated_at) %></h3>
<%= link_to 'Edit company', edit_company_path %> | <%= link_to 'Volver', companies_path %>

app/views/google/contact.html.erb
<div class="w3-container w3-container w3-center w3-animate-opacity w3-flat-midnight-blue">
  <% unless @contacts.nil?%>
      <% @contacts.each do |c|%>
      <table class="w3-table">
          <tr>
            <th>Name</th>
            <th>Phone number</th>
            <th>Email</th>
            <th colspan="4"></th>
          </tr>
          <tr>
            <td><%= c[:name] %></td>
            <td><%= c[:phone_number] %></td>
            <td><%= c[:email]%></td>
          </tr>
      </table>
    <% end%>
  <% end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-colors-flat.css">
    <title>AppPath</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
     <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
 <div class="w3-card-4 w3-container w3-teal w3-margin-right w3-margin-left">
    <%= form_for(@user) do |u| %>
        <% @user.errors.full_messages.each do |message| %>
        <p style="padding: 2px; background-color: #25639E; display: table;"><%= message %><p>
        <% end %>
        First Name* :  <%= u.text_field :first_name %><br><br>
        Last Name* :   <%= u.text_field :last_name %><br><br>
        Address* :     <%= u.text_field :address %><br><br>
        Password* :    <%= u.password_field :password %><br><br>
        Email* :       <%= u.text_field :email %><br><br>
        City* :        <%= u.text_field :city %><br><br>
        State* :       <%= u.text_field :state %><br><br>
        Cellphone* :   <%= u.text_field :cellphone %><br><br>
        Phone :        <%= u.text_field :phone %><br><br>
        Company :      <%= u.select :company_id, Company.all.collect { |comp| [ comp.name, comp.id ] }, {:prompt => "Select company"}, {:include_blank => true}%><br><br>
        <%= u.submit %>
    <% end %>
    <%= link_to 'Volver', users_path %>
  </div>

  

app/views/users/edit.html.erb
<h1 class="w3-container w3-black w3-margin-right w3-margin-left">Edit user</h1>
  <%= render 'form' %>
 

app/views/users/index.html.erb
<div class="w3-display-topmiddle w3-center w3-animate-top w3-flat-midnight-blue w3-margin-right">
 <h1 class="w3-container w3-teal">Users</h1>
<table class="w3-table">
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Address</th>
    <th>Email</th>
    <th>City</th>
    <th>State</th>
    <th>Cellphone</th>
    <th>Phone</th>
    <th>Company</th>
    <th colspan="4"></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.address %></td>
      <td><%= user.email %></td>
      <td><%= user.city %></td>
      <td><%= user.state %></td>
      <td><%= user.cellphone %></td>
      <td><%= user.phone %></td>
      <td><%= user.company.try(:name) %></td>
      <td class="w3-button w3-yellow"><%= link_to 'Show', user %><td>
      <td class="w3-button w3-blue"><%= link_to 'Edit user', edit_user_path(user) %></td>
      <td class="w3-button w3-red"><%= link_to 'Delete user', user,
                       method: :delete,
                       data: { confirm: '¿Are you sure?'} %>
      </td>
    </tr>
  <% end %>
  <%= link_to 'New User', new_user_path %> | <%= link_to 'Companies', companies_path %>
</table>
</div>
<li><%= link_to 'Import contacts', "/contacts/gmail" %></li>
    <div>
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, id: "sign_out" %>
      <% end %>
    </div>

app/views/users/new.html.erb
<h1 class="w3-container w3-black w3-margin-right w3-margin-left">New user</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<ul class="w3-ul">
  <li class="w3-hover-black"><h1><%= @user.first_name %></h1></li>
  <li class="w3-hover-red"><h2><%= @user.company.try(:name)%></h2></li>
  <li class="w3-hover-blue"><p><%= @user.last_name %></p></li>
  <li class="w3-hover-green"><p><%= @user.address %></p></li>
  <li class="w3-hover-red"><p><%= @user.email %></p></li>
  <li class="w3-hover-blue"><p><%= @user.city %></p></li>
  <li class="w3-hover-green"><p><%= @user.state %></p></li>
  <li class="w3-hover-red"><p><%= @user.cellphone %></p></li>
  <li class="w3-hover-blue"><p><%= @user.phone %></p></li>
</ul>
<h3><%= time_ago_in_words(@user.updated_at) %></h3>
<%= link_to 'Volver', users_path %>